project:
  type: website
  output-dir: docs

website:
  title: "Environmental Violations in Texas"
  navbar:
    left:
      - href: index.qmd
      - 01-cleaning.qmd
      - 02-analysis.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



